"""added lassa priority model 

Revision ID: 0ab8e01473b2
Revises: 6f0f35c17cc0
Create Date: 2025-10-21 14:23:38.643593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab8e01473b2'
down_revision: Union[str, None] = '6f0f35c17cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lassa_fever_reports', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('lassa_fever_reports', sa.Column('latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lassa_fever_reports', 'latitude')
    op.drop_column('lassa_fever_reports', 'longitude')
    # ### end Alembic commands ###
