"""migrations 

Revision ID: 948d466de754
Revises: 0b19c5a9cb39
Create Date: 2025-08-11 22:28:17.457773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '948d466de754'
down_revision: Union[str, None] = '0b19c5a9cb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_casereport_case_id', table_name='casereport')
    op.drop_index('ix_casereport_personID', table_name='casereport')
    op.drop_table('casereport')
    op.drop_table('lassa_fever_unstructured')
    op.drop_index('ix_report_case_id', table_name='report')
    op.drop_index('ix_report_personID', table_name='report')
    op.drop_table('report')
    op.drop_table('lassa_fever_structured')
    op.drop_constraint('animal_reports_reporter_id_fkey', 'animal_reports', type_='foreignkey')
    op.drop_column('animal_reports', 'reporter_id')
    op.drop_constraint('environmental_reports_reporter_id_fkey', 'environmental_reports', type_='foreignkey')
    op.drop_column('environmental_reports', 'reporter_id')
    op.drop_constraint('health_reports_reporter_id_fkey', 'health_reports', type_='foreignkey')
    op.drop_column('health_reports', 'reporter_id')
    op.add_column('health_workers', sa.Column('facility', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_workers', 'facility')
    op.add_column('health_reports', sa.Column('reporter_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('health_reports_reporter_id_fkey', 'health_reports', 'health_workers', ['reporter_id'], ['id'])
    op.add_column('environmental_reports', sa.Column('reporter_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('environmental_reports_reporter_id_fkey', 'environmental_reports', 'health_workers', ['reporter_id'], ['id'])
    op.add_column('animal_reports', sa.Column('reporter_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('animal_reports_reporter_id_fkey', 'animal_reports', 'health_workers', ['reporter_id'], ['id'])
    op.create_table('lassa_fever_structured',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rodent_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('symptoms', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lga', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lassa_fever_structured_pkey')
    )
    op.create_table('report',
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('personID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('disease', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('classification', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('animal_species', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_affected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lga', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('health_facility', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_onset', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_of_confirmation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reporting_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('symptoms', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('risk_factors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('environmental_factors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sample_collected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lab_results', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='report_pkey')
    )
    op.create_index('ix_report_personID', 'report', ['personID'], unique=False)
    op.create_index('ix_report_case_id', 'report', ['case_id'], unique=False)
    op.create_table('lassa_fever_unstructured',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lassa_fever_unstructured_pkey')
    )
    op.create_table('casereport',
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('personID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('disease', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('classification', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('animal_species', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_affected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lga', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('health_facility', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_onset', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_of_confirmation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reporting_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('symptoms', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('risk_factors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('environmental_factors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sample_collected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lab_results', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='casereport_pkey')
    )
    op.create_index('ix_casereport_personID', 'casereport', ['personID'], unique=False)
    op.create_index('ix_casereport_case_id', 'casereport', ['case_id'], unique=False)
    # ### end Alembic commands ###
