"""added more fields to health workers table 

Revision ID: a13323f3bfe9
Revises: 0ab8e01473b2
Create Date: 2025-10-24 13:56:47.775409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13323f3bfe9'
down_revision: Union[str, None] = '0ab8e01473b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_workers', sa.Column('state', sa.String(), nullable=True))
    op.add_column('health_workers', sa.Column('lga', sa.String(), nullable=True))
    op.add_column('health_workers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('health_workers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_workers', 'longitude')
    op.drop_column('health_workers', 'latitude')
    op.drop_column('health_workers', 'lga')
    op.drop_column('health_workers', 'state')
    # ### end Alembic commands ###
