"""added reporterid to cases 

Revision ID: d145836767d8
Revises: 948d466de754
Create Date: 2025-08-11 23:18:08.683401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd145836767d8'
down_revision: Union[str, None] = '948d466de754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_reports', sa.Column('reporter_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'animal_reports', 'health_workers', ['reporter_id'], ['id'])
    op.add_column('environmental_reports', sa.Column('reporter_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'environmental_reports', 'health_workers', ['reporter_id'], ['id'])
    op.add_column('health_reports', sa.Column('reporter_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'health_reports', 'health_workers', ['reporter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_reports', type_='foreignkey')
    op.drop_column('health_reports', 'reporter_id')
    op.drop_constraint(None, 'environmental_reports', type_='foreignkey')
    op.drop_column('environmental_reports', 'reporter_id')
    op.drop_constraint(None, 'animal_reports', type_='foreignkey')
    op.drop_column('animal_reports', 'reporter_id')
    # ### end Alembic commands ###
